### ISSUE TITLE
Adding the Kakarot zkEVM implementation of EIP-3074

### ISSUE THREAD

**Issue by Eikix** [vasa-develop/awesome-3074#1]
Hi there!

Smol request to add one of the implementations of the EIP in Cairo:
- https://github.com/kkrt-labs/kakarot/pull/1104

That way, we can list which EVM implementations built the EIP? 

It's being used in debates with the alphanet team to assess correctness of implementations: https://github.com/paradigmxyz/alphanet/issues/58
https://github.com/paradigmxyz/alphanet/pull/59

**Comment by vasa-develop** [comment]
Sure thing! For now, I'll add it to the tooling section, but I'll probably create an EIP-3074 implementations section separately to track progress on the node implementations soon.
